In [1]:
#  Import all the packages
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid
import matplotlib.pyplot as plt
from autils import *
import mnist

In [2]:
# Download mnist dataset that handwritten numbers
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
# Print x_train shape and x_test shape
print("Shape of x_train: ", x_train.shape)
print("Shape of x_text: ", x_test.shape)

Shape of x_train:  (60000, 28, 28)
Shape of x_text:  (10000, 28, 28)


In [4]:
# Print y_train shape and y_test shape
print("Shape of x_train: ", y_train.shape)
print("Shape of x_text: ", y_test.shape)

Shape of x_train:  (60000,)
Shape of x_text:  (10000,)


In [5]:
# Normalize data
x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.normalize(x_test, axis=1)

In [6]:
# Create model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

In [7]:
# Compile and fit the model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics="accuracy")
history = model.fit(x_train, y_train, epochs=3, validation_data=(x_test,y_test), verbose=1)

Epoch 1/3
1875/1875 [==============================] - 2s 759us/step - loss: 0.2615 - accuracy: 0.9226 - val_loss: 0.1335 - val_accuracy: 0.9602
Epoch 2/3
1875/1875 [==============================] - 1s 706us/step - loss: 0.1077 - accuracy: 0.9665 - val_loss: 0.0992 - val_accuracy: 0.9690
Epoch 3/3
1875/1875 [==============================] - 1s 712us/step - loss: 0.0723 - accuracy: 0.9775 - val_loss: 0.1095 - val_accuracy: 0.9660


In [8]:
# Compare x_train and y_train
index = 643
image_of_two = x_train[index]


prediction = model.predict(image_of_two.reshape(1,28, 28))  # prediction

print(f" predicting a Two: \n{prediction}")
print(f" Largest Prediction index: {np.argmax(prediction)}")
print(f" Actually value: {y_train[index]}")

1/1 [==============================] - 0s 29ms/step
 predicting a Two: 
[[4.8387328e-08 7.4581595e-07 2.9889879e-08 9.9985564e-01 3.5136927e-06
  1.0380030e-04 7.4539354e-11 2.1985645e-05 2.4271685e-07 1.4111960e-05]]
 Largest Prediction index: 3
 Actually value: 3


In [9]:
# Predict t_text
predictArray = (model.predict(x_test))

313/313 [==============================] - 0s 340us/step


In [10]:
predictArray.shape

(10000, 10)

In [11]:
predictArray[:5]

array([[5.50929613e-08, 4.92937545e-07, 8.59837292e-06, 1.64030702e-04,
        9.01656207e-08, 2.44755370e-06, 2.52980753e-12, 9.99766409e-01,
        1.95457096e-06, 5.59539658e-05],
       [2.92989029e-07, 7.67655857e-03, 9.91612673e-01, 3.08354865e-05,
        2.44679427e-07, 5.92571683e-04, 1.80113093e-05, 2.97311288e-07,
        6.83470862e-05, 1.92489125e-07],
       [1.09375602e-08, 9.99240398e-01, 2.96977378e-04, 4.10519215e-06,
        4.06502768e-05, 1.08110875e-07, 2.88750243e-07, 4.11239802e-04,
        6.07011270e-06, 2.76602094e-07],
       [9.88615394e-01, 2.87152099e-04, 9.96254617e-04, 2.09244645e-05,
        2.27417401e-03, 2.99073406e-04, 5.61435288e-03, 1.60480198e-03,
        1.04487472e-05, 2.77493091e-04],
       [1.58078819e-07, 5.42647101e-08, 8.71093835e-06, 3.16866533e-07,
        9.99837279e-01, 4.45742353e-06, 9.03057867e-07, 5.17586250e-06,
        6.24006771e-06, 1.36688119e-04]], dtype=float32)

In [12]:
# predictArray convert to predict_y
predict_y = np.argsort(predictArray, axis=1)[:, -1].astype("uint8")

In [13]:
predict_y[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [14]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [15]:
# Compare y_test and predict_y
different_indexs = np.array(np.where(predict_y != y_test)).reshape(-1,1)

In [16]:
print("Number of different index: ", len(different_indexs))
print(different_indexs[:5])

Number of different index:  340
[[ 18]
 [ 96]
 [151]
 [217]
 [241]]


In [17]:
print('Train Accuracy: ', (len(y_test)-len(different_indexs)) / len(y_test) * 100)

Train Accuracy:  96.6
